// 
// This file contains the data for the jokes in jokes.cpp.
// It is a vector of Joke structs, which contain the category, setup, and punchline of each joke.
//
#include <vector>
#include <string>
using namespace std;

struct Joke {
    string type;   // e.g. "dad", "knock-knock", "pun", "math", "tech", "work", "aging", "Bible"
    string setup;
    string punchline;
};

const vector<Joke> jokes = {
    {"dad", "Why did the stadium get hot after the game?", "All of the fans left."},
    {"dad", "What did the janitor say when he jumped out of the closet?", "Supplies!"},
    {"dad", "How do you organize a space party?", "You planet."},
    {"dad", "What do you call a parade of rabbits hopping backwards?", "A receding hare-line."},
    {"dad", "Why do cows wear bells?", "Because their horns don't work."},
    {"dad", "What do you call a sleepwalking nun?", "A roamin' Catholic."},
    {"dad", "Why did the coffee file a police report?", "It got mugged."},
    {"dad", "What do you call a pile of kittens?", "A meow-ntain."},
    {"dad", "I'll tell you a joke about a roof.", "Never mind, it's over your head."},
    {"dad", "What did the ocean say to the pirate?", "Nothing, it just waved."},
    {"dad", "Why can't you trust atoms?", "Because they make up everything."},
    {"dad", "What do you call a snobby criminal going down the stairs?", "A condescending con, descending."},
    {"dad", "To the man in the wheelchair who stole my camouflage jacket...", "You can hide, but you can't run."},
    {"dad", "What did the fish say when he hit the wall?", "Dam."},
    {"dad", "Why did the private tip-toe past the medicine cabinet?", "He didn't want to wake the sleeping pills."},
    {"dad", "What's the difference between a hippo and a zippo?", "One is really heavy, and the other is a little lighter."},
    {"dad", "Why don't eggs tell jokes?", "They'd crack each other up."},
    {"dad", "I used to play piano by ear...", "But now I use my hands."},
    {"dad", "Why did the bicycle fall over?", "Because it was two-tired."},
    {"dad", "What do you call a man with no body and no nose?", "Nobody nose."},
    {"dad", "I'm reading a book on anti-gravity.", "It's impossible to put down."},
    {"dad", "Did you hear about the kidnapping at school?", "It's okay, he woke up."},
    {"dad", "What do you call a bear with no teeth?", "A gummy bear."},
    {"dad", "Why did the mushroom go to the party?", "Because he was a fungi."},
    {"dad", "What do you call fake spaghetti?", "An impasta."},
    {"dad", "Why did the scarecrow win an award?", "Because he was outstanding in his field."},
    {"dad", "Why don't skeletons fight each other?", "They don't have the guts."},
    {"dad", "What do you call cheese that isn't yours?", "Nacho cheese."},
    {"dad", "Why did the golfer bring two pairs of pants?", "In case he got a hole in one."},
    {"dad", "What do you call an alligator in a vest?", "An investigator."},
    {"dad", "Why did the tomato turn red?", "Because it saw the salad dressing."},
    {"dad", "How does a penguin build its house?", "Igloos it together."},
    {"dad", "What do you call a factory that makes good products?", "A satisfactory."},
    {"dad", "Why did the cookie go to the hospital?", "Because he felt crummy."},
    {"dad", "What do you call a dinosaur with an extensive vocabulary?", "A thesaurus."},
    {"dad", "Why did the math book look sad?", "Because it had too many problems."},
    {"dad", "What do you call a cow with no legs?", "Ground beef."},
    {"dad", "Why was the big cat disqualified from the race?", "Because it was a cheetah."},
    {"dad", "What do you call a fish wearing a bowtie?", "Sofishticated."},
    {"dad", "Waitress: How did you find your steak Sir?","I just looked next to the potatoes and there it was."},
    {"dad", "If you play guitar and want to know the secret to making it sound better,","Please stay tuned..."},
    {"dad", "5 ants rented an apartment with another 5 ants.","Now they're tenants"},
    {"dad", "What's the best present you can gift?","A broken drum.\nNobody can beat that."},
    {"dad", "What did the buffalo say when his son left?","Bison"},
    {"dad", "My daughter asked me if I had seen the dog bowl.","Me: No, I didn't even know he could."},
    {"dad", "Why didn't the toilet paper make it across the street?","It got stuck in the crack."},
    {"dad", "So far, Humpty Dumpty is having a terrible winter.","Which is frustrating, because he had a great fall."},
    {"dad", "What do you call a nervous javelin thrower?","Shakespeare."},
    {"dad", "What do you call a sketchy neighborhood in Italy?","The spaghetto."},
    {"dad", "Why did the picture go to jail?","Because it was framed."},
    {"dad", "Did you hear about the fire at the circus?", "It was in tents."},
    {"dad", "I don't trust stairs.", "They're always up to something."},
    {"dad", "What do you call a dog that does magic tricks?", "A labracadabrador."},
    {"dad", "Why did the old man fall in the well?", "Because he couldn't see that well."},
    {"dad", "I ordered a chicken and an egg from Amazon.", "I'll let you know."},
    {"dad", "What do you call a belt made out of watches?", "A waist of time."},
    {"dad", "What kind of shoes do ninjas wear?", "Sneakers."},
    {"dad", "How do you make a tissue dance?", "You put a little boogie in it."},
    {"dad", "Why did the math teacher open a window?", "To let out the acute angles."},
    {"dad", "What do you call a pig that does karate?", "A pork chop."},
    {"dad", "I thought about going on an all-almond diet.", "But that's just nuts."},
    {"dad", "Why don't some couples go to the gym?", "Because some relationships don't work out."},
    {"dad", "What do you call a bee that can't make up its mind?", "A maybe."},
    {"dad", "I would tell you a joke about time travel.", "But you didn't like it."},
    {"dad", "Why do seagulls fly over the ocean?", "Because if they flew over the bay, they'd be bagels."},
    {"dad", "What do you call a bear with no ears?", "B."},
    {"dad", "Did you hear about the guy who invented the knock-knock joke?", "He won the 'no-bell' prize."},
    {"dad", "I only know 25 letters of the alphabet.", "I don't know y."},
    {"dad", "What has more letters than the alphabet?", "The post office."},
    {"dad", "Why did the frog take the bus to work?", "His car got toad."},
    {"dad", "I've got a great joke about construction.", "I'm still working on it."},
    {"dad", "What did the grape do when he got stepped on?", "He let out a little wine."},
    {"dad", "I used to be addicted to soap.", "But I'm clean now."},
    {"dad", "Why are elevator jokes so good?", "They work on so many levels."},
    {"dad", "What do you call a pony with a cough?", "A little hoarse."},
    {"dad", "Did you hear about the guy who stole a calendar?", "He got 12 months."},
    {"dad", "Why did the invisible man turn down the job offer?", "He couldn't see himself doing it."},
    {"dad", "What does a sprinter eat before a race?", "Nothing, they fast."},
    {"dad", "Why do melons have weddings?", "Because they cantaloupe."},
    {"dad", "What do clouds wear under their shorts?", "Thunderwear."},
    {"dad", "What kind of car does an egg drive?", "A yolkswagen."},
    {"dad", "Why was the computer cold?", "It left its Windows open."},
    {"dad", "Where do bees go to the bathroom?", "The BP station."},
    {"dad", "Why do golfers love donuts?", "Because there's a hole in the middle."},
    {"dad", "News: A man lost his left arm and left leg in a car crash.", "He's all right now."},
    {"dad", "What kind of candy do astronauts like?", "Mars bars."},
    {"dad", "What did one wall say to the other?", "I'll meet you at the corner."},
    {"dad", "I think I'm sick of taking the elevator.", "I think I'm coming down with something."},
    {"dad", "What did the termite say when he walked into the bar?", "Is the bar tender here?"},
    {"dad", "What do you call a sheep that knows karate?", "A lamb chop."},
    {"dad", "Why did the tree go to the dentist?", "It needed a root canal."},
    {"dad", "Did you hear about the Italian chef that died?", "He pasta way."},
    {"dad", "What is an astronaut's favorite part of a computer?", "The space bar."},
    {"dad", "Why did the computer go to the doctor?", "Because it had a virus."},
    {"dad", "Did you hear about the restaurant on the moon?", "Great food, no atmosphere."},
    {"dad", "Why do river banks work so well?", "They have high current-cy."},
    {"dad", "Have you heard about the new corduroy pillows?", "They're making headlines."},
    {"dad", "Every morning for the past three months, I announce loudly to the family that I'm going for a jog, and then I don't","It's my longest running joke of this year."},
    {"dad", "Why do ghosts love elevators?","Because it lifts their spirits."},
    {"dad", "Why did the girl keep her trumpet out in the snow?","Because she liked cool jazz."},
    {"dad", "A weasel walks into a bar, and the bartender says,\n\"Wow, I've never seen a weasel before. What can I get you?\"","\"Pop,\" goes the weasel"},
    {"dad", "How do you console an English teacher?","There, their, they're."},
    {"dad", "My dental hygienist won a national award for teeth cleaning.","She proudly displays the plaque on her desk."},
    {"dad", "What do you call a man with a rubber toe?", "Roberto."},
    {"dad", "What do you call a fat psychic?", "A four-chin teller."},
    {"dad", "My documentary film \"I have stolen all your chairs\"", "just received a 90 minute standing ovation."},
    {"dad", "I found a coin on the ground in the parking lot today. It had teeth marks on it.","It was a bitcoin."},
    {"dad", "Due to the storm I ran out of toilet paper and had to use newspaper.", "The Times are rough."},
    {"dad", "What do you call a dad that has fallen through the ice?","A Popsicle."},
    {"dad", "Dad at breakfast: I'll have bacon and eggs, please. Waiter: How do you like your eggs?", "Dad: I don't know, I don't have them yet."},
    {"dad", "I sing when I'm in my car, but only in reverse.", "I'm a backup singer."},
    {"dad", "Why did the scarecrow become a successful neurosurgeon?", "He was outstanding in his field."},
    {"dad", "I used to hate facial hair.", "But then it grew on me."},
    {"dad", "How do you make a water bed more bouncy?", "You add spring water."},
    {"dad", "What happens when you witness a ship wreck?", "It creates a sinking feeling."},
    {"dad", "Why did the melon jump into the lake?", "It wanted to be a water-melon."},
    {"pun", "To the guy who invented zero,", "Thanks for nothing."},
    {"pun", "I had a crazy dream last night! I was swimming in an ocean of orange soda.", "Turns out it was just a Fanta sea."},
    {"pun", "I used to be a baker, but I couldn't make enough dough.", "I kneaded the money."},
    {"pun", "I'm on a seafood diet.", "I see food and I eat it."},
    {"pun", "I wondered why the baseball was getting bigger.", "Then it hit me."},
    {"pun", "Did you hear about the guy whose left side was cut off?", "He's all right now."},
    {"pun", "I'd tell you a chemistry joke but I know I wouldn't get a reaction.", "Na."},
    {"pun", "The future, the present, and the past walked into a bar.", "Things got a little tense."},
    {"pun", "I wasn't originally going to get a brain transplant.", "But then I changed my mind."},
    {"pun", "Why did the scarecrow win an award?", "Because he was outstanding in his field."},
    {"pun", "What do you call a sleeping bull?", "A bulldozer."},
    {"pun", "I used to be a shoe salesman.", "But I couldn't fit in."},
    {"pun", "I'm glad I know sign language.", "It's pretty handy."},
    {"pun", "The rotation of the earth really makes my day.", "It really does."},
    {"pun", "I couldn't figure out how to put my seatbelt on.", "Then it clicked."},
    {"pun", "A man filed a police report for his missing luggage.", "But he never made a case."},    
    {"pun", "I'm friends with 25 letters of the alphabet.", "I don't know Y."},
    {"pun", "Light travels faster than sound.", "That's why some people appear bright until you hear them speak."},
    {"pun", "I was wondering why the frisbee kept getting bigger.", "Then it hit me."},
    {"pun", "When you dream in color, is it a pigment of your imagination?", "I suppose so."},
    {"pun", "I couldn't remember how to throw a boomerang.", "But then it came back to me."},    
    {"knock-knock", "Shore", "Shore hope you like bad jokes!"},
    {"knock-knock", "Euripides", "Euripides clothes, you buy them!"},
    {"knock-knock", "Lettuce", "Lettuce in, it's cold out here!"},
    {"knock-knock", "Tank", "You're welcome."},
    {"knock-knock", "Cow says", "No, a cow says mooooo!"},
    {"knock-knock", "Who", "Is there an owl in here?"},
    {"knock-knock", "Etch", "Bless you!"},
    {"knock-knock", "Boo", "Don't cry, it's just a joke."},
    {"knock-knock", "Harry", "Harry up and answer the door!"},
    {"knock-knock", "Nobel", "No bell, that's why I knocked."},
    {"knock-knock", "A little old lady", "I didn't know you could yodel!"},
    {"knock-knock", "Water", "Water you doing asking who I am, open up!"},
    {"knock-knock", "Leaf", "Leaf me alone!"},
    {"knock-knock", "Figs", "Figs the doorbell, it's broken!"},
    {"knock-knock", "Annie", "Annie body home?"},
    {"knock-knock", "Wooden shoe", "Wooden shoe like to know!"},
    {"knock-knock", "Amish", "Really? You don't look like a shoe."},
    {"knock-knock", "Dishes", "Dishes the police, come out with your hands up!"},
    {"knock-knock", "Canoe", "Canoe come out and play?"},
    {"knock-knock", "Razor", "Razor hands, this is a stick up!"},
    {"knock-knock", "Nana", "Nana your business."},
    {"knock-knock", "Spell", "W-H-O."},    
    {"knock-knock", "Atch", "Bless you!"},
    {"knock-knock", "Woo", "Don't get too excited, it's just a joke."},
    {"knock-knock", "Hawaii", "Hawaii you doing today?"},
    {"knock-knock", "Cash", "No thanks, I prefer peanuts."},
    {"knock-knock", "Owl", "Owl you know if you don't open the door?"},
    {"math", "Why should you never talk to Pi?", "Because he'll go on forever."},
    {"math", "What did the acorn say when he grew up?", "Geometry."},
    {"math", "Why did the student eat his math homework?", "Because the teacher said it was a piece of cake."},
    {"math", "Are monsters good at math?", "Not really, unless you count Dracula."},
    {"math", "Why is it sad that parallel lines have so much in common?", "Because they'll never meet."},
    {"math", "Why didn't the number 4 get into the nightclub?", "Because he is 2 square."},
    {"math", "Why was the equal sign so humble?", "Because it knew it wasn't less than or greater than anyone else."},
    {"math", "Why do plants hate math?", "Because it gives them square roots."},
    {"math", "What do you call a number that can't keep still?", "A roamin' numeral."},
    {"math", "Why was the math book sad?", "Because it had too many problems."},
    {"math", "What do you call a snake that is 3.14 meters long?", "A pi-thon."},
    {"math", "Why did the student do multiplication problems on the floor?", "The teacher told him not to use tables."},
    {"math", "Why was the obtuse triangle always upset?", "Because it is never right."},
    {"math", "Did you hear about the mathematician who's afraid of negative numbers?", "He'll stop at nothing to avoid them."},
    {"math", "Why do teenagers travel in groups of 3?", "Because they can't even."},
    {"math", "Why did the two 4s skip lunch?", "They already 8."},
    {"math", "What did the triangle say to the circle?", "You're pointless."},
    {"math", "I saw my math teacher with a piece of graph paper yesterday.", "I think she must be plotting something."},
    {"math", "Why did the student get upset when his teacher called him average?", "It was a mean thing to say."},
    {"math", "How do you stay warm in a cold room?", "Go to the corner, it's 90 degrees."},
    {"math", "Why was six afraid of seven?", "Because seven eight nine!"},
    {"math", "Why did the chicken cross the Mobius strip?", "To get to the same side."},
    {"math", "What are 3.14 percent of sailors?", "Pi-rates."},
    {"math", "Why can't a nose be 12 inches long?", "Because then it would be a foot."},
    {"math", "Why did the geometric shape go to the gym?", "To get in better shape."},
    {"math", "Who invented the Round Table?", "Sir Cumference."},
    {"math", "What did the zero say to the eight?", "Nice belt!"},
    {"math", "Why shouldn't you argue with a decimal?", "Decimals always have a point."},
    {"math", "What do you call a crushed angle?", "A rectangle."},
    {"math", "Why did the 30-60-90 triangle marry the 45-45-90 triangle?", "They were right for each other."},
    {"math", "What do you call dudes who love math?", "Algebros."},
    {"math", "What do you get when you divide the circumference of a jack-o-lantern by its diameter?", "Pumpkin Pi."},
    {"tech", "What's the biggest lie in the entire universe?", "I have read and agree to the Terms & Conditions."},
    {"tech", "Why did the man get fired from his job at the keyboard factory?", "He wasn't putting in enough shifts."},
    {"tech", "There are 10 types of people in the world.", "Those who understand binary, and those who don't."},
    {"tech", "Why do programmers always mix up Halloween and Christmas?", "Because Oct 31 equals Dec 25."},
    {"tech", "A SQL query walks into a bar, walks up to two tables, and asks...", "Can I join you?"},
    {"tech", "How many programmers does it take to change a light bulb?", "None, that's a hardware problem."},
    {"tech", "Why did the programmer quit his job?", "Because he didn't get arrays."},
    {"tech", "What is a programmer's favorite hangout place?", "Foo Bar."},
    {"tech", "Why do Java programmers wear glasses?", "Because they don't C#."},
    {"tech", "0 is false and 1 is true, right?", "1."},
    {"tech", "What did the router say to the doctor?", "It hurts when IP."},
    {"tech", "Why was the developer unhappy at their job?", "They wanted arrays."},
    {"tech", "What do you call a computer floating in the ocean?", "A Dell Rolling in the Deep."},
    {"tech", "Why did the PowerPoint presentation cross the road?", "To get to the other slide."},
    {"tech", "Have you heard about the new band 1023 Megabytes?", "They haven't got a gig yet."},
    {"tech", "What is the most used language in programming?", "Profanity."},
    {"tech", "Why did the computer keep sneezing?", "It had a virus."},
    {"tech", "What's a computer's favorite snack?", "Microchips."},
    {"tech", "Why did the developer go broke?", "Because he used up all his cache."},
    {"tech", "What do you call a program that sings?", "A wrapper."},
    {"tech", "Why are Assembly programmers always soaking wet?", "They work below C-level."},
    {"tech", "How does a computer get drunk?", "It takes screenshots."},    
    {"tech", "Why did the QA engineer go to the bar?", "To order 1 beer, 0 beers, 999999999 beers, and a lizard."},
    {"tech", "Why do programmers prefer dark mode?", "Because light attracts bugs."},
    {"tech", "Why was the mobile phone wearing glasses?", "Because it lost its contacts."},
    {"dad", "They say birds of a feather flock together,\nbut do you know which birds really stick together?", "Velcrows"},
    {"dad", "What do you call a group of unorganized cats?", "A cat-astrophe."},
    {"dad", "What do you call a group of musical whales?", "An orca-stra."},
    {"dad", "What do you call a group of cows playing instruments?", "A moo-sical band."},
    {"dad", "What do you call a group of birds that stick together?", "Velcrows."},
    {"dad", "I invented a thought controlled air freshener.\nMy wife told me it was dumb.", "But it makes scents when you think about it."},
    {"dad", "A guy tried to sell me a mirror.", "But I knew it was a scam, I could see right through it."},
    {"tech", "Why did the programmer get stuck in the shower?", "Because the instructions on the shampoo bottle said: Lather, Rinse, Repeat."},
    {"dad", "What do you call a can opener that's broken?", "A can't opener."},
    {"dad", "Why don't skeletons ever go trick or treating?", "Because they have no body to go with."},
    {"dad", "What do you call an elephant that doesn't matter?", "An irrelephant."},
    {"dad", "Want to hear a joke about paper?", "Nevermind, it's tearable."},
    {"dad", "My friend has designed an invisible aeroplane.", "I can't see it taking off."},
    {"dad", "This graveyard looks overcrowded.", "People must be dying to get in there."},
    {"dad", "I built an electric fence around my garden.", "My neighbour is dead against it."},
    {"dad", "Two goldfish are in a tank. One says to the other,", "\"Do you know how to drive this thing?\""},
    {"dad", "Why do you never see elephants hiding in trees?", "Because they're so good at it."},
    {"dad", "A furniture store keeps calling me.", "All I wanted was one night stand."},
    {"dad", "I just watched a program about beavers.", "It was the best dam program I've ever seen."},
    {"dad", "Did I tell you the time I fell in love during a backflip?", "I was heels over head."},
    {"dad", "I don't play soccer because I enjoy the sport.", "I'm just doing it for kicks."},
    {"dad", "What do you call a Mexican who has lost his car?", "Carlos."},
    {"dad", "People don't like having to bend over to get their drinks.", "We really need to raise the bar."},
    {"dad", "What do you call a shoe made of a banana?", "A slipper."},
    {"dad", "How many apples grow on a tree?", "All of them."},
    {"dad", "You know what actually makes me smile?", "My facial muscles."},
    {"dad", "I am reading a horror story in Braille.", "Something bad is going to happen, I can feel it."},
    {"tech", "To whoever stole my copy of Microsoft Office, I will find you.", "You have my Word!"},
    {"dad", "Singing in the shower is all fun and games until you get shampoo in your mouth.", "Then it's a soap opera."},
    {"dad", "I went to the store to pick up 8 cans of Sprite.", "When I got home I realised I'd only picked 7up."},
    {"dad", "When is a door not a door?", "When it's ajar."},
    {"dad", "What's blue and smells like red paint?", "Blue paint."},
    {"dad", "I purchased a deodorant stick today. Instructions say \"Remove cap and push up bottom.\"", "I can hardly walk but when I fart the room smells lovely."},
    {"dad", "What is the least spoken language in the world?", "Sign language."},
    {"dad", "To the person who stole my glasses. I will find you.", "I have contacts."},
    {"dad", "What's red and bad for your teeth?", "A brick."},
    {"dad", "Two years ago my doctor told me I was going deaf.", "I haven't heard from him since."},
    {"dad", "As I suspected, someone has been adding soil to my garden.", "The plot thickens."},
    {"dad", "After you die, what part of your body is the last to stop working?", "Your pupils. They dilate."},
    {"dad", "How do you get a farm girl to like you?", "A tractor."},
    {"dad", "Son: Dad, did you get a haircut?", "Dad: No, I got them all cut."},
    {"dad", "Son: Dad, can you put on my shoes for me?", "Dad: I'll try but they might not fit!"},
    {"dad", "Son: Dad, can you tell me what a solar eclipse is?", "Dad: No sun."},
    {"dad", "Son: Dad, can you put the cat out?", "Dad: I didn't know it was on fire."},
    {"dad", "Son: I'll call you later.", "Dad: Don't call me later, call me Dad."},
    {"dad", "Son: Dad, I'm hungry!", "Dad: Hi Hungry, I'm Dad."},
    {"dad", "Son: How do I look?", "Dad: With your eyes."},
    {"dad", "What lies at the bottom of the ocean and twitches?", "A nervous wreck."},
    {"dad", "You know what the loudest pet you can get is?", "A trum-pet."},
    {"dad", "How does a meteorologist go up a mountain?", "They climate."},
    {"dad", "My obese parrot died today.", "Sad, but it's a huge weight off my shoulders."},
    {"tech", "I told a joke on a zoom meeting and no-one laughed.", "It turns out I'm not remotely funny."},
    {"dad", "Guess who I bumped into on my way to get my glasses fixed?", "Everybody."},
    {"dad", "I told my wife she was drawing her eyebrows too high.", "She looked surprised."},
    {"dad", "What did one plate whisper to the other plate?", "Dinner is on me."},
    {"dad", "Did you hear about the baguette at the zoo?", "It was bread in captivity."},
    {"dad", "I don't want to brag, I finished the puzzle in a week.", "But it said 2-4 years on the box."},
    {"dad", "Whoever stole my antidepressants I hope you are happy now.", ""},
    {"dad", "People say I'm getting fat. But in my defense,", "I've had a lot on my plate recently."},
    {"dad", "I was shocked when I found out my toaster wasn't waterproof.", ""},
    {"dad", "I accidentally handed my wife a glue stick instead of a chapstick.", "She still isn't talking to me."},
    {"dad", "I used to be addicted to soap.", "But I'm clean now."},
    {"dad", "I would tell you a joke about time travel.", "But you didn't like it."},
    {"dad", "I know a lot of jokes about unemployed people.", "But none of them work."},
    {"dad", "I used to be a banker.", "But I lost interest."},
    {"dad", "I got a job at a bakery because I kneaded dough.", ""},
    {"dad", "I wanted to learn how to drive a stick shift.", "But I couldn't find a manual."},
    {"tech", "Why don't programmers like nature?", "It has too many bugs!"},
    {"tech", "Why was the unemployed JavaScript developer sad?", "Because he didn't get callbacks!"},
    {"tech", "A programmer was arrested for writing unreadable code.", "He refused to comment."},
    {"tech", "What did 0 say to 1?", " You're a bit too much."},
    {"tech", "Things aren't always #000000 and #FFFFFF", ""},
    {"tech", "Binary:", "It's as easy as 01, 10, 11."},
    {"tech", "An SEO expert came by to take me to lunch.", "He asked if I wanted to go to a restaurant, drive-in, eatery, grill, joint, lunchroom, dive, greasy spoon, or hamburger stand."},
    {"tech", "Where did the software developer go?", "He probably ransomware."},
    {"tech", "Someone cracked my password.", "Now I need to rename my dog."},
    {"dad", "Why does it take pirates a long time to learn the alphabet?", "Because they can spend years at C!"},
    {"dad", "What do you call a pirate who skips class?", "Captain Hooky."},
    {"dad", "Why did the pirate go to the Caribbean?", "Because he wanted some arr and arr."},
    {"dad", "A slice of apple pie costs $2.50 in Jamaica, $3.75 in Bermuda, and $3 in the Bahamas.", "Those are the pie-rates of the Caribbean."},
    {"dad", "Why don't pirates shower before they walk the plank?", "Because they'll just wash up on shore later."},
    {"dad", "How much do rainbows weigh?", "Not much. They're actually pretty light."},
    {"dad", "What do you call a happy cowboy? ", "A jolly rancher."},
    {"dad", "Why was six afraid of seven?", "Because seven eight nine."},
    {"dad", "What did one hat say to the other?", "You wait here, I'll go on ahead."},
    {"dad", "What did the lunch box say to the refrigerator?", "Don't hate me because I'm a little cooler."},
    {"dad", "Why do people who live in Greece hate waking up at dawn?", "Because Dawn is tough on Greece."},
    {"dad", "If April showers bring May flowers, what do May flowers bring?", "Pilgrims."},
    {"dad", "Did you hear about the pirate who became a great chef?", "He mastered the seven sea-sonings."},
    {"dad", "I flew my paper airplane, but it hovered in one spot like a helicopter.", "Then I remembered I'd made it out of stationery."},
    {"dad", "My wife calls me \"The Computer\"", "Nothing to do with my intelligence - I go to sleep if left unattended for 15 minutes."},
    {"dad", "We've all seen a refrigerator run, a microwave, and a kitchen sink.", "But I just saw a toilet bowl. It was STRIKING!"},
    {"dad", "I had a great time horseback riding today.", "I felt like a real cowboy until I ran out of quarters."},
    {"dad", "Did you hear about the guy who was addicted to the hokey pokey?", " He turned himself around."},
    {"dad", "What do cats eat for breakfast?", "Mice Krispies"},
    {"dad", "Why did the chicken cross the playground?", "To get to the other slide!"},
    {"dad", "Did you hear about the guy who's afraid of escalators?", "He takes steps to avoid them."},
    {"knock-knock", "Police", "Police let us in, it's getting cold outside."},
    {"dad", "How does a penguin build its house?", "Igloos it together."},
    {"dad", "What do you call a factory that makes good products?", "A satisfactory."},
    {"dad", "Why did the cookie go to the hospital?", "Because he felt crummy."},
    {"dad", "How do you find a cheetah in the dark?", " Use a spotlight."},
    {"dad", "What do you call a boomerang that won't come back?", "A stick."},
    {"dad", "Why did the cake cross the road?", "It saw a fork up ahead."},
    {"dad", "What do you call a snowman with a six-pack?", "An abdominal snowman."},
    {"dad", "What do horses do when it's time for bed?", "Hit the hay."},
    {"dad", "What's the difference between a piano and a fish?", "You can tune a piano, but you can't tuna fish."},
    {"dad", "Why did the guy get fired from the calendar factory?", "He took a day off."},
    {"dad", "Why did the cowboy adopt a wiener dog?", "He wanted to get a long little doggie."},
    {"knock-knock", "Dora Belle", "Dora Belle is broken, that's why I'm knocking."},
    {"knock-knock", "Isabel", "Isabel ringing?"},
    {"knock-knock", "Luke", "Luke through the peephole and find out."},
    {"knock-knock", "Olive", "Olive you and I miss you."},
    {"knock-knock", "Alpaca", "Alpaca the suitcase, you load up the car!"},
    {"knock-knock", "Doris", "Doris locked, that's why I'm knocking."},
    {"dad", "What's orange and sounds like a parrot?", "A carrot!"},
    {"dad", "I stayed up all night wondering where the sun went.", "Then it dawned on me."},
    {"dad", "Why was the stadium so cool? ", "It was filled with fans."},
    {"dad", "Why did the banana go to the doctor?", "It was not peeling well."},
    {"dad", "I used to run a dating service for chickens.", "But I was struggling to make hens meet."},
    {"dad", "I'm not a fan of spring cleaning.", "To be honest, I'm not into summer, fall, or winter cleaning either."},
    {"dad", "Where do lizards go after their tail falls off?", "The retail store."},
    {"dad", "Our local bridge was closed today.", "I still can't get over it."},
    {"dad", "The other day I held the door open for a clown.", "I thought it was a nice jester."},
    {"dad", "Why do cows have hooves instead of feet?", "Because they lactose."},
    {"dad", "One time, I tripped walking through Paris.", "Eiffel over."},
    {"dad", "I always keep my guitar in my car now...", "It's good for traffice jams."},
    {"dad", "I went on a ski trip.", "It started off fine, but went downhill fast."},
    {"dad", "If you think swimming with dolphins is expensive, you should try swimming with sharks.", "Cost me an arm and a leg"},
    {"dad", "A sweater I bought was picking up static electricity.", "They gave me another one free of charge."},
    {"dad", "I can't remember how to write 1, 1000, 51, 6, and 500 in Roman numerals.", "I M LIVID"},
    {"dad", "I told the nurse I was bitten by a wolf. \"Where?\" she asked.", "No. Regular"},
    {"dad", "What's the best way to carve wood?", "Whittle by whittle."},
    {"dad", "My father said, \"As one door closes, another opens.\"", "Beautiful man, terrible cabinet maker."},
    {"dad", "Chinese takeout: $30.", "Getting home and finding out part of your order is missing: riceless."},
    {"dad", "I renamed by toilet Jim instead of John.", "People are really impressed when I tell them I go to the Jim every morning."},
    {"work", "Bread is a lot like the sun.", "It rises in the yeast and sets in the waist."},
    {"work", "I like jokes about stationery,", "but rulers are where I draw the line."},
    {"work", "Went to the doctor with a suspicious-looking mole.", "He said they all look that way and I should have left him in the garden."},
    {"work", "It's called gross pay...", "Because it's disgusting to see how much money you would have made before taxes."},
    {"work", "Bravely killed a bug at home.", "Then realized it was a piece of lint."},
    {"work", "I was going to tell a carpentry joke,", "but I couldn't find any that woodwork."},
    {"work", "I get plenty of exercise at work...", "jumping to conclusions, pushing my luck, and dodging deadlines"},
    {"work", "The reward for good work is usually just more work.", ""},
    {"work", "To make an error is human;", "to blame it on someone else shows management potential."},
    {"work", "Did you know that Davy Crockett had three ears?", "His left ear, his right ear, and his wild frontier."},
    {"work", "I was walking past a farm and a sign said, \"Duck, eggs.\" I thought, that's an unnecessary comma.", "And then it hit me."},
    {"work", "Learn to spell", "AutoCorrect isn't always write."},
    {"work", "What's Forrest Gump's password?", "1Forrest1."},
    {"work", "The CEO of IKEA was appointed Prime Minister of Sweden.", "He's currently assembling his cabinet."},
    {"work", "Boss told me that as a security guard, it's my job to watch the office.", "I'm on season 6 but I'm not really sure what it's got to do with security."},
    {"work", "What did the fried rice say to the shrimp?", "Don't wok away from me!"},
    {"work", "This morning I saw a person dragging a clam on a leash behind him.", "It must be hard to walk with a pulled mussel."},
    {"work", "Me: I want to travel.", "Bank Account: Where? To work?"},
    {"work", "Why did the candle quit his job?", "He was burned out."},
    {"work", "I quit my job at the doughnut factory.", "I was tired of the hole thing."},
    {"work", "Did you hear about the maze designer who retired?", "He just kept getting lost in his work."},
    {"work", "I got a job as a can crusher.", "It was soda pressing."},
    {"work", "A photon checks into a hotel and the bellhop asks if he has any luggage.", "The photon replies, \"No, I'm traveling light.\""},
    {"work", "What's a forklift?", "Food, usually."},
    {"work", "What do you call someone with no body and no nose?", "Nobody knows."},
    {"work", "Gravity is one of the most fundamental forces in the universe.", "But if you remove it, you get gravy."},
    {"work", "What's a pirate's favorite content?", "WebinARRRRR!"},
    {"work", "What do biologists wear to work on Casual Friday?", "Genes."},
    {"work", "I quit my job at the pencil factory.", "It was pointless."},
    {"work", "I quit my job at the elastic factory.", "I was stretched to my breaking point."},
    {"work", "My boss told me to have a good day,", "So I went home."},
    {"work", "When I got to work this morning, my boss stormed up and said, \"You missed work yesterday, didn't you?\"", "I said, \"No, not particularly.\""},
    {"work", "A worker tells his boss: \"I've got three companies after me, so if you want me to stay, I'll need a 5% raise.\" The boss agrees. \"What are the three companies?\" the boss asks.", "\"The electric company, the water company, and the gas company.\""},
    {"work", "Did you hear that Larry got a new job working for Old MacDonald?", "He's the new CIEIO."},
    {"work", "Did you hear about the actor who fell through the floorboards?", "He was going through a stage."},
    {"work", "I love deadlines.", "I love the whooshing sound they make as they go by."},
    {"work", "The most successful investor was Noah.", "He floated stock while everything around him went into liquidation."},
    {"work", "A candidate overflows a cup of water during the interview. Interviewer: \"Nervous?\"", "Candidate: \"No, I always give 110%.\""},
    {"work", "I knew my coworker was replaced by a bot when they replied to a 4:45 PM meeting request with \"Sure, I'd love to!\"", "No human is that enthusiastic."},
    {"work", "Company Policy: We don't have a dress code, but please remember this is an office, not a pajama party.", "Unless it's Pajama Day. HR will notify you."},
    {"dad", "I got fired from my job at the funeral home because I kept asking my customers whether they would prefer \"Smoking\" or \"Non-smoking\".", "Apparently the correct terms are \"Cremation\" and \"Burial\"."},
    {"dad", "I got fired from my funeral home job.", "I miscalculated casket size to body size one too many times. I mean, I'm no mathamortician."},
    {"dad", "Lost my job at the funeral home.", "I made a grave mistake."},
    {"dad", "I lost my job at the pet store.", "A woman came in to buy a spider and I told her she could get one cheaper on the web."},
    {"aging", "My husband cooks for me like I'm a goddess.", "By placing burnt offerings before me."},
    {"aging", "Bickering with your spouse is like trying to read the Terms of Use for a new service.", "In the end, you just give up and click \"I agree.\""},
    {"aging", "I'm not afraid of aging.", "I'm just afraid of stairs, ladders, tiny print, and chairs that sit too low to the ground."},
    {"aging", "What's the secret to having a smoking hot body in old age?", "Cremation."},
    {"aging", "What is a prize old people can win for aging?", "Atrophy."},
    {"aging", "What's the best part of old age?", "That it doesn't last very long."},
    {"aging", "Which underwear brand do seniors love best?", "It Depends."},
    {"aging", "Why do old people love English muffins so much?", "Because of the nooks and grannies."},
    {"aging", "What goes up but never comes down?", "Your age!"},
    {"aging", "Where can single men over 65 find younger women who are interested in them?", "In the bookstore, under \"Fiction.\""},
    {"aging", "Why should you marry someone older than you?", "As your looks fade, so will their eyesight."},
    {"aging", "Why do retirees smile so much?", "Because they can't hear a word you're saying."},
    {"aging", "How is the moon like dentures?", "Both come out at night."},
    {"aging", "What do you call someone who enjoys Mondays?", "Retired."},
    {"aging", "When is the best time to start thinking about your retirement?", "Before the boss does."},
    {"aging", "What's the key to a structured retirement?", "A rigid nap schedule."},
    {"aging", "Why was the retiree's wife tired?", "She got twice as much husband for half the pay."},
    {"aging", "How many retirees does it take to change a light bulb?", "One, but it'll take all day."},
    {"aging", "These are not gray hairs!", "They are wisdom highlights."},
    {"aging", "Old age makes us great multitaskers.", "Why, I can sneeze and pee at the same time!"},
    {"aging", "What's worse than middle age?", "Knowing you'll grow out of it."},
    {"aging", "One benefit of old age is that your secrets are always safe with your friends...", "...because they can't remember them!"},
    {"aging", "Now that I've gotten older, everything's finally starting to click for me.", "My knees, my back, my neck..."},
    {"aging", "I've decided whatever age I am...", "Is the new 30."},
    {"aging", "Age is an issue of mind over matter.", "If you don't mind getting older, then it really doesn't matter."},
    {"aging", "Don't let aging get you down.", "It's too hard to get back up again."},
    {"aging", "Of all your children, the only one who won't grow up and move away is...", "Your husband."},
    {"aging", "An old woman is sitting at a bar when an older gentleman sits down beside her.", "\"So,\" he says, \"do I come here often?\""},
    {"aging", "My doctor told me I need to sweat daily...", "So I told him I'd start disobeying my wife."},
    {"aging", "After a big fight, my wife yelled at me, \"You know, I was a fool when I married you.\"", "So I replied, \"That may be true, but I was in love and didn't notice it.\""},
    {"aging", "Be kind to your kids.", "They choose your nursing home."},
    {"aging", "I always wanted to marry Mrs. Right.", "I just didn't know her first name would be \"Always.\""},
    {"aging", "Husbands are like lawn mowers:", "They're hard to get started, emit foul odors and don't work half the time."},
    {"aging", "Retirement is wonderful.", "It's doing nothing without worrying about getting caught."},
    {"aging", "You know it's time to retire when...", "Your co-workers are wearing clothing from your youth and calling it retro."},
    {"aging", "The truth is, retirement kills more people...", "Than hard work ever did."},
    {"aging", "My company recently gave me an aptitude test...", "And I found out the work I was best suited for was retirement."},
    {"aging", "Retirement is what happens...", "Between doctors' appointments."},
    {"aging", "Sometimes the best part of your career is...", "Retirement."},
    {"aging", "Retirement is like one big sick day...", "Without sick pay."},
    {"aging", "Money isn't everything...", "But it sure keeps you in touch with your children."},
    {"aging", "You know you're getting old when...", "Your birthday cake is a fire hazard."},
    {"aging", "I used to know a couple who grew fruit trees together.", "They lived to a ripe old age."},
    {"aging", "If I ever decide to buy a horse ranch in my old age...", "I'm going to name it Pasture Prime."},
    {"aging", "I called the incontinence hotline recently.", "They asked if I could hold."},
    {"aging", "You know you're getting old when...", "Your doctor refers you to an archaeologist."},
    {"aging", "Old people are just young people...", "Who have been alive for a very, very long time."},
    {"aging", "The older we get...", "The earlier it gets late."},
    {"aging", "I'm so old...", "I remember when the Dead Sea was middle-aged."},
    {"aging", "With age comes wisdom...", "And hair in really weird places."},
    {"aging", "I'm getting...", "Older and wider instead of older and wiser!"},
    {"aging", "Allow me to politely suggest...", "That this be the year you start lying about your age."},
    {"aging", "With old age comes wisdom...", "And early-bird specials!"},
    {"aging", "At my age, the only pole dancing I do is...", "While holding on to the safety bar in the bathtub."},
    {"dad", "My room mate says I'm schizophrenic", "The joke's on him, I don't even have a room mate."},
    {"dad", "I have a fear of speed bumps.", "But I'm slowly getting over it."},
    {"dad", "How did the skeleton know that April showers were on the way?", "He could feel it in his bones."},
    {"dad", "Which country's capital is fastest growing?", "Ireland. Every year it's Dublin."},
    {"dad", "My wife asked for something with diamonds in it for her birthday.", "So I got her a deck of cards."},
    {"dad", "What do you call a well-dressed lion in the spring?", "A dandy lion."},
    {"dad", "Coffee was just voted the best drink in the nation.", "But it was unfair, there were absent tea ballots."},
    {"dad", "Does February like March?", "No, but April May."},
    {"dad", "Why couldn't the flower ride its bike?", "It lost its petals."},
    {"aging", "I've finally reached the age where my back goes out a whole lot more than I do.", ""},
    {"aging", "I asked my wife if she thought I was starting to get a lot of gray hair.", "She looked at me and said, \"At this point, you should just be happy it's still hair.\""},
    {"dad", "I burnt my Hawaiian pizza last night. It is rurnt.", "I should have put it on Aloha setting."},
    {"dad", "What do you call an Easter egg that goes to the gym?", "An eggs-ercise enthusiast."},
    {"dad", "What kind of books do Easter Bunnies like?", "Ones with hoppy endings."},
    {"dad", "What do you call a rabbit with fleas?", "Bugs Bunny."},
    {"dad", "What do you call a line of rabbits hopping backwards?", "A receding hare-line."},
    {"dad", "What do you call a rabbit who tells jokes?", "A funny bunny."},
    {"dad", "What do you call a rabbit who is a musician?", "A hip-hop artist."},
    {"dad", "I went to a psychic's house. I knocked on the door and she said, \"Come in, I know you're there.\" I was really impressed. I thought, \"Wow, she can read minds!\"", "Then I realized she just had really good hearing."},
    {"dad", "I asked my dog what two minus two is.", "He said nothing."},
    {"dad", "I told my wife she was drawing her eyebrows too high.", "She looked surprised."},
    {"dad", "What do you call a man who can't stand?", "Neil."},
    {"dad", "Why did the stoplight turn red?", "You would too if you had to change in the middle of the street."},
    {"dad", "What do you call a guy who never farts in public?", "A private tutor."},
    {"dad", "What do you call a steak that's been knighted?", "Sir Loin."},
    {"dad", "I don't trust people who do acupuncture.", "They're back-stabbers."},
    {"dad", "What did the sushi say to the bee?", "Wasabi!"},
    {"dad", "Why do scuba divers fall backwards off the boat?", "Because if they fell forwards they'd still be in the boat."},
    {"dad", "What do you call a woman who sets fire to her bills?", "Bernadette."},
    {"dad", "What do you call a sad cup of coffee?", "A depresso."},
    {"dad", "I asked the librarian if they had books about paranoia.", "She whispered, \"They're right behind you.\""},
    {"dad", "What do you call an illegally parked frog?", "Toad."},
    {"dad", "I used to be a transplant surgeon.", "I had a change of heart."},
    {"dad", "What do you call a knight who is afraid to fight?", "Sir Render."},
    {"dad", "What time did the man go to the dentist?", "Tooth hurty."},
    {"dad", "Why can't you run through a campsite?", "You can only ran -- it's past tents."},
    {"dad", "Did you hear about the cheese factory explosion?", "There was nothing left but de-brie."},
    {"dad", "I would tell you a pizza joke,", "but it's too cheesy."},
    {"dad", "What do you call a magician who lost his magic?", "Ian."},
    {"dad", "What do you call a train that sneezes?", "Achoo-choo train."},
    {"dad", "Why don't mountains get cold in winter?", "They wear snowcaps."},
    {"dad", "I have an addiction to cheddar cheese.", "But it's only mild."},
    {"dad", "Did you hear about the claustrophobic astronaut?", "He just needed a little space."},
    {"dad", "How do you make holy water?", "Boil the hell out of it."},
    {"dad", "Why did the nurse always carry a red pen?", "In case she needed to draw blood."},
    {"dad", "I went to buy some camouflage trousers,", "but I couldn't find any."},
    {"dad", "What do you call a wolf that uses foul language?", "A swear-wolf."},
    {"dad", "What do you call a deer with no eyes?", "No idea."},
    {"dad", "What do you call a dinosaur that crashes their car?", "Tyrannosaurus wrecks."},
    {"dad", "What do you call a witch who lives at the beach?", "A sand-witch."},
    {"dad", "How does a vampire start a letter?", "Tomb it may concern."},
    {"dad", "My wife told me to stop impersonating a flamingo.", "I had to put my foot down."},
    {"dad", "Why did the physics teacher break up with the biology teacher?", "There was no chemistry."},
    {"dad", "Why did the hipster burn his tongue?", "He drank his coffee before it was cool."},
    {"dad", "I want to start a hot air balloon company.", "Haven't got it off the ground yet."},
    {"dad", "Why did the belt go to jail?", "It held up a pair of pants."},
    {"dad", "Two peanuts were walking down the street.", "One was a-salted."},
    {"dad", "What does a nosy pepper do?", "Gets jalapeño business."},
    {"dad", "I was going to tell you a joke about an infinity mirror.", "On reflection, I decided not to."},
    {"dad", "Did you hear about the new broom?", "It swept the nation."},
    {"dad", "I accidentally swallowed some food coloring.", "The doctor says I'll be fine, but I feel like I've dyed a little inside."},
    {"dad", "Why do bees hum?", "Because they don't know the words."},
    {"dad", "Why was the calendar anxious?", "Its days were numbered."},
    {"dad", "I tried calling the tinnitus helpline.", "It just kept ringing."},
    {"math", "30% of Americans do not know how to do basic math.", "Thank God I'm part of the other 80%."},
    {"dad", "Did you know the guy who invented the wind chill factor died? He was 85.", "But he felt like he was only 74."},
    {"aging", "I finally know why they call me a grown up.", "I groan every time I get up."},
    {"math", "Where do math teachers go on vacation?", "Times Square"},
    {"dad", "I told my soap a joke...", "It didn't laugh, but it did crack up"},
    {"dad", "Dogs can't operate MRI machines.", "But catscan."},
    {"dad", "Why shouldn't pigs drive?", "They hog the road."},
    {"dad", "What does corn say when it gets a compliment?", "Aw, shucks."},
    {"dad", "I invented a pencil with an eraser on each end.", "There's no point to it."},
    {"dad", "The wedding was so beautiful.", "Even the cake was in tiers."},
    {"dad", "I don't know much about the best things in Switzerland.", "But their flag is a big plus."},
    {"dad","I went to a school for magicians but failed the last exam.","They were all trick questions."},
    {"dad", "I applied for a job down at the diner. I told them I really could bring a lot to the table.", "They asked if I could also clear it."},
    {"dad", "What do you call a line of men waiting to get haircuts?", "A barber-queue."},
    {"dad", "Did you hear about the guy who fell into an upholstery machine?", "He's fully recovered."},
    {"dad", "Why is it a bad idea to fall in love with a tennis player?", "Because love means nothing to them."},
    {"dad", "Teacher: Billy, can you use the word 'gruesome' in a sentence?", "Billy: Yes ma'am... I used to short, then I grew some."},
    {"dad", "In ancient Rome, there were four poisons. Poisons I, II, and III caused instant death.", "Poison IV caused constant itching."},
    {"dad", "What's it called when a cow spies on you?", "A steakout."},
    {"dad", "Did you hear about the big Lego sale?", "People were lined up for blocks."},
    {"dad", "I asked the surgeon if I could administer my own anesthesia...", "He said, \"Sure knock yourself out.\""},
    {"dad", "A woman fainted and fell onto the baggage carousel at the airport.", "But she's slowly coming around now."},
    {"dad", "I grilled a chicken for two hours...", "Still wouldn't tell me why it crossed the road"},
    {"dad", "Someone just called my phone, sneezed, and hung up...", "I'm getting sick and tired of these cold calls."},
    {"dad", "What can you do for someone who is becoming invisible?", "Put him in the ICU."},
    {"pun", "My wife said she'd leave me unless I stop making photography puns. I said \"Snap out of it, don't be so negative. Let's see how things develop!\"", "Her face was a picture. She was out of the house in a flash..."},
    {"dad", "My wife called to tell me she saw a bear on the way to work. I asked her how she knew it was on its way to work.", "She hung up on me."},
    {"tech", "What did Yoda say when he saw himself in 4k?", "HDMI"},
    {"dad", "When I was younger I had a job as a shop window mannequin.", "I held that position for a long time."},
    {"dad", "What's the difference between a dad joke and an athletic rabbit?", "One's a bit funny... and the other's a fit bunny."},
    {"dad", "I've decided to start telling jokes in sign language.", "That way, I know for sure nobody's heard them before."},
    {"dad", "A friend told me he doesn't understand cloning.", "I said, \"That makes two of us.\""},
    {"dad", "My friend said he didn't understand archaeology.", "I said, \"You've got to dig a little deeper.\""},
    {"tech", "A programmer's wife told him, \"While you're at the store, get a loaf of bread. If they have eggs, get a dozen.\"", "He came home with 12 loaves of bread."},
    {"tech", "A programmer was asked, \"What's your biggest strength? He said, \"I'm very good at avoiding unnecessary duplication.\"", "Then he said, \"I'm very good at avoiding unnecessary duplication.\""},
    {"work", "I applied for a job hanging mirrors.", "It's something I can see myself doing."},
    {"dad", "I tried to organize a hide and seek tournament...", "But good players are hard to find."},
    {"dad", "How do you explain why the Hulk never loses his pants when he transforms?", "The experiment altered his jeans."},
    {"pun", "Did you hear about the kid who started a business tying shoelaces on the playground?", "It was a knot-for-profit."},
    {"dad", "How do they tie things down on the space station?", "They use astro knots."},
    {"aging", "A friend of mine is a knot theorist and I told him a joke that wasn't about knot theory.", "He said he's too old for not-knot jokes."},
    {"dad", "A man walks into a hardware store and picks up a can of fly spray. He asks, \"Is this good for wasps?\"", "The clerk said, \"No, it kills them!\""},
    {"work", "Out of all the inventions in the last 100 years...", "The dry erase board might be the most remarkable one."},
    {"dad", "What state is known for its tiny sodas?", "Minnesota"},
    {"dad", "When does a regular joke become a dad joke?", "When it becomes apparent."},
    {"dad", "How does Darth Vader like his toast?", "He likes it on the dark side."},
    {"dad", "What's the best kind of music to listen to when you're fishing?", "Something catchy."},
    {"dad", "I found a book called \"Solve 50% of Your Problems\",", "so I bought two copies."},
    {"dad", "What did Elvis say to his landscaper?", "Thank you for the mulch!"},
    {"dad", "I'd like to shout out sidewalks for keeping me off the streets.", ""},
    {"aging", "I wish my gray hair started in Las Vegas", "because what happens in Vegas, stays in Vegas."},
    {"dad", "I told my son I was going to buy him a book on procrastination,", "but I keep putting it off."},
    {"aging", "As I get older, I remember all the people I lost along the way.", "Maybe my budding career as a tour guide was not the right choice."},
    {"aging", "Don't mess with old people,", "because life in prison is no longer really a deterrent."},
    {"aging", "It's weird being the same age as old people.", ""},
    {"aging", "The problem with retirement is that you never get a day off.", ""},
    {"aging", "You know you're old when the answer to the \"boxers or briefs\" question", "is \"Depends.\""},
    {"aging", "What does a pirate say when they turn 80?", "\"Aye matey years old.\""},
    {"aging", "What time does an old person go to bed?", "About two hours after they fall asleep in the recliner."},
    {"math", "What do you get when you cross a calculator with a friend?", "Someone you can count on."},
    {"math", "There once was a hen who counted her own eggs.", "She was a mathemachicken!"},
    {"math", "Why don't you do arithmetic in the jungle?", "Because if you add 4 and 4, you get ate!"},
    {"math", "What's a math teacher's favorite type of story?", "One with a good plot."},
    {"math", "How do you make seven even?", "Take away the \"s.\""},
    {"math", "Why did seven eat nine?", "Because you're supposed to eat three squared meals a day!"},
    {"math", "Why was the equal sign always calm?", "Because it balanced both sides."},
    {"math", "There are three kinds of people in this world.", "Those who can count and those who can't."},
    {"math", "Surgeon: Nurse, I have so many patients. Who do I work on first?", "Nurse: Simple. Follow the order of operations."},
    {"math", "Do you know what seems odd to me?", "Numbers that can't be divided by two."},
    {"math", "Why is 69 afraid of 70?", "Because they had a fight and 71."},
    {"math", "A farmer counted 396 cows in his field.", "But when he rounded them up, he had 400."},
    {"dad", "Why did the coffee taste like dirt?", "Because it was ground just moments ago."},
    {"dad", "What did the alien say to the landscaper?", "Take me to your weeder."},
    {"dad", "How many apples grow on an apple tree?", "All of them."},
    {"dad", "The child refused to nap.", "He was guilty of resisting a rest."},
    {"dad", "I don't trust those trees.", "They seem kind of shady."},
    {"dad", "Where do boats go when they're sick?", "The boat doc."},
    {"dad", "Have you ever tried to catch fog?", "I tried but mist."},
    {"dad", "What does a lawyer wear to court?", "A lawsuit."},
    {"dad", "How much does it cost for Santa to park his sleigh?", "Nothing, it's on the house."},
    {"dad", "What did Tennessee?", "The same thing as Arkansas."},
    {"dad", "I tripped and hit my head on a snare drum.", "Now, I think I have a percussion."},
    {"dad", "I got cast in a film about a bakery. It’s not a huge part...", "Just a small roll"},
    {"dad", "I gave my friend an apple, but he said he preferred pears...", "So I gave him another apple."},
    {"dad", "Why did the sea monster eat five ships carrying potatoes?", "No one can eat just one potato ship."},
    {"dad", "I was walking in the jungle and saw a lizard on his hind legs telling jokes. I said to the local tribesman, \"That lizards really funny.\"", "The tribesman replied, \"That's not a lizard. He's a stand up chameleon.\""},
    {"work", "I keep swapping the N and M keys on everyon's keyboard at work. Some are calling me a monster.", "I say I'm a nomster."},
    {"dad", "Why did the man decide to buy nine rackets?", "Because tennnis too many!"},
    {"dad", "They asked me if I wanted my pizza delivered.", "I said absolutely. I hate liver."},
    {"dad", "I've been trying come up with some jokes about sewing...", "If only I had some material."},
    {"dad", "I told my psychiatrist that I've been hearing voices.", "He told me that I don't have a psychiatrist."},
    {"dad", "Scientists have found that cows produce more milk when the farmer talks to them.", "Apparently, it's a case of in one ear and out the udder."},
    {"Bible", "Why was Samson so good at arguments?", "He always pulled things apart."},
    {"Bible", "Why did Noah become a gardener?", "He already knew about pairs."},
    {"Bible", "Why did the church gardener pray often?", "He wanted faith to grow."},
    {"Bible", "Why did Joseph dream so much?", "He had mattress revelations."},
    {"Bible", "Why was the Bible comedian popular?", "His jokes were truly divine."},
    {"Bible", "What kind of man was Boaz before he married?", "Ruth-less."},
    {"Bible", "Why was David calm during storms?", "He trusted the Rock."},
    {"Bible", "What did Adam say the day before Christmas?", "\"It's Christmas, Eve!\""},
    {"Bible", "Why do Bible jokes travel well?", "They have good Exodus routes."},
    {"Bible", "Why did the sheep carry a Bible?", "It wanted to follow the Good Shepherd."},
    {"Bible", "Why did Noah brush the animals' teeth?", "To prevent ark cavities."},
    {"Bible", "What's a church cat called?", "A hymn-alayan."},
    {"Bible", "Why was Elijah so smart?", "He had prophet margins."},
    {"Bible", "Why was Joseph great at business?", "He knew how to handle coats."},
    {"Bible", "Why did Moses never lose his phone?", "He had cloud backup."},
    {"Bible", "What's a church drummer's favorite Bible verse?", "\"Let everything that has breath praise the Lord.\""},
    {"Bible", "Why did Noah keep bees on the ark?", "He wanted an ark-hive."},
    {"Bible", "What's a Bible character's favorite candy?", "Moses Pieces."},
    {"Bible", "Why did the Bible teacher carry glue?", "To keep the class together."},
    {"Bible", "Why was the church so cold?", "Too many fans of Revelation."},
    {"Bible", "What's a missionary's favorite car?", "A convert-ible."},
    {"Bible", "Why did Lazarus become a motivational speaker?", "He really knew how to rise up."},
    {"Bible", "Why did the church kitchen stay busy?", "They always had soul food."},
    {"Bible", "Why did Noah install windows?", "The ark needed fresh heir."},
    {"Bible", "Why did Noah become a carpenter?", "He already had ark experience."},
    {"Bible", "Why didn't Noah go fishing?", "He only had two worms."},
    {"Bible", "What excuse did Adam give to his children about why they no longer lived in Eden?", "\"Your mother ate us out of house and home.\""},
    {"Bible", "Why did the church musician lock the piano?", "Someone kept playing by ear."},
    {"Bible", "Why did the choir bring maps?", "They wanted harmony directions."},
    {"Bible", "Why did Solomon cut his hair?", "He wanted wisdom highlights."},
    {"Bible", "Why didn't they play cards on the ark?", "Noah was standing on the deck."},
    {"Bible", "Why did the disciples become bakers?", "They were experts in loaf and fishes."},
    {"Bible", "Why couldn't Jonah trust the ocean?", "There was something fishy about it."},
    {"Bible", "Why did Daniel avoid wild parties?", "He already spent time with lions."},
    {"Bible", "Why did Noah carry a pencil?", "To draw animals in pairs."},
    {"Bible", "What did Noah say while fishing?", "\"I'm waiting for another bite.\""},
    {"Bible", "Why did Daniel refuse dessert?", "He already had lion-around time."},
    {"Bible", "What kind of math do angels like?", "Heaven-tometry."},
    {"Bible", "Why did David download music apps?", "He loved Psalm playlists."},
    {"Bible", "What did the priest say to the sleepy congregation?", "\"Wake me up before you go-gospel.\""},
    {"Bible", "What kind of coffee was served in church?", "Hebrews."},
    {"Bible", "What kind of shoes do Bible characters wear?", "Sand-als."},
    {"Bible", "Why was the church coffee so strong?", "Hebrews brewed it."},
    {"Bible", "What kind of exercise do Christians like?", "Cross-fit."},
    {"Bible", "Why did Samson avoid haircuts?", "He didn't want split strength."},
    {"Bible", "Why did the church choir carry umbrellas?", "In case of reign."},
    {"Bible", "Why didn't Cain trust Abel?", "Because he was able."},
    {"Bible", "Why did Solomon avoid arguments?", "He preferred wise cracks."},
    {"Bible", "Why did David bring a sling to church?", "For giant problems."},
    {"Bible", "Why did the pastor tell dad jokes?", "To keep the congregation awake."},
    {"Bible", "Why did the fish follow Jesus?", "They heard He was a reel teacher."},
    {"Bible", "Why did the Bible student bring string to class?", "To tie Old and New Testaments together."},
    {"Bible", "Why didn't the Pharisees trust stairs?", "They were always up to something."},
    {"Bible", "Why did Moses carry a tablet?", "He started mobile commandments."},
    {"Bible", "Why did the disciples go fishing at night?", "They wanted net profits."},
    {"Bible", "Why did the choir go to baseball practice?", "To improve their pitch."},
    {"Bible", "Why did Noah bring sugar on the ark?", "For the flood flakes."},
    {"Bible", "Why was the church library noisy?", "Too many book-of-Mark discussions."},
    {"Bible", "Why was the temple always clean?", "They had prophet maintenance."},
    {"Bible", "Why was Jonah always wet?", "He worked over-sea."},
    {"Bible", "Why did the donkey go to church?", "To hear a good tail."},
    {"Bible", "Why did the shepherd become famous?", "He had flock stars."},
    {"Bible", "Why did the choir sing loudly?", "They wanted to raise the roof and the hallelujahs."},
    {"Bible", "Why did the pastor carry a ladder?", "To reach higher praise."},
    {"Bible", "What did the grape say during communion?", "\"Wine not?\""},
    {"Bible", "Why was the church parking lot peaceful?", "Everyone practiced car-ma."},
    {"Bible", "Why was Noah bad at poker?", "Everybody knew he had a pair."},
    {"Bible", "Why did the disciples carry pencils?", "To draw nearer to God."},
    {"Bible", "What's an angel's favorite dessert?", "Halo-halo."},
    {"Bible", "Why did Noah never go hungry?", "He had two of every snack."},
    {"Bible", "What's Moses' favorite sport?", "Basket-ball."},
    {"Bible", "Why was the Bible character always calm?", "He had a lot of Psalm-control."},
    {"Bible", "Why was Goliath surprised when David hit him?", "The thought had never entered his head before."},
    {"Bible", "Why did the wise men smell great?", "They came bearing myrrh deodorant."},
    {"Bible", "What's a Bible teacher's favorite drink?", "Root beer."},
    {"Bible", "Why did Moses make a great baseball coach?", "He knew when to part the field."},
    {"Bible", "Why did the church picnic fail?", "Too many holy rollers."},
    {"Bible", "Why did Moses cross the Red Sea?", "To get to the other tide."},
    {"Bible", "Why did Paul stop jogging?", "He got tired of all the Acts."},
    {"Bible", "Why did the baker go to church?", "He needed daily bread."},
    {"Bible", "Why did the church have so many clocks?", "They wanted eternal timing."},
    {"Bible", "Why was the church bell so confident?", "It had perfect chime management."},
    {"Bible", "Who was the shortest man in the Bible?", "Nehemiah."},
    {"Bible", "Why did Elijah use email?", "He liked sending fiery messages."},
    {"Bible", "Why don't Bible characters use social media?", "Too many followers already."},
    {"Bible", "Why did the angel get promoted?", "He had heavenly performance reviews."},
    {"Bible", "Why did Eve open a fruit stand?", "She had apple experience."},
    {"Bible", "What kind of lights did Noah use on the ark?", "Floodlights."},
    {"Bible", "Why did Noah have to punish the chickens on the ark?", "They kept using fowl language."},
    {"Bible", "Why was Eve the fastest runner?", "She was first in the human race."},
    {"Bible", "Why did the church baker smile?", "His buns were blessed."},
    {"Bible", "Why did Adam and Eve do math every day?", "They were told to multiply."},
    {"Bible", "Why did the priest carry snacks?", "For spiritual nourishment."},
    {"Bible", "Why did Lazarus smile after waking up?", "He finally got some rest."},
    {"Bible", "Why did the Israelites wander in the desert for 40 years?", "Even in Bible times, men refused to ask for directions."},
    {"Bible", "Why did the donkey laugh in church?", "It heard a mule-titude of jokes."},
    {"Bible", "What was the greatest female financier in the Bible?", "Pharaoh's daughter. She went down to the bank of the Nile and drew out a little prophet."},
    {"Bible", "Why was the ark noisy?", "The animals kept roaring with laughter."},
    {"Bible", "Why did the church Wi-Fi slow down?", "Too many people logging into the cloud."},
    {"Bible", "Why did Jesus use sunscreen?", "To avoid burning bushes."},
    {"Bible", "How do we know Peter was rich?", "By his net income."},
    {"dad", "What do you get when you cross a duck with a rocket?", "A firequacker!"},
    {"dad", "What do you get when you cross a firecracker and a ghost?", "Bamboo!"},
    {"Bible", "Who was the greatest comedian in the Bible?", "Samson. He brought the house down."},
    {"Bible", "Who was the smartest man in the Bible?", "Abraham. He knew a Lot."},
    {"Bible", "Why did the unemployed man get excited while looking through his Bible?", "He thought he saw a job."},
    {"Bible", "What was the first word out of Adam's mouth when he first saw Eve?", "Whoa man! Thus, the word \"woman\" was created."},
    {"Bible", "How many people can you fit in one Honda?",  "Well, the Bible said that all 12 disciples were in one Accord."},
    {"dad", "What’s a pirate’s favorite letter? ", "You’d think it’s R, but their first love is the C."},
    {"dad", "What’s the ocean’s favorite comedy show? ", "Whale of Fortune"}
};
